name: Publish tags
on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Build and check
        run: |
          uv build
          uvx twine check dist/*
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: "builds"
          path: "dist/*"
          if-no-files-found: error
      - name: Check tag name if we're to publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          if ! [[ "v$(uv version --short)" == "${GITHUB_REF##*/}" ]]; then
            echo "Tag does not match!"
            exit 1
          fi
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/generate-systemd-timer
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    permissions:
      id-token: write
      contents: write
    steps:
      - name: "Download build artifacts"
        uses: actions/download-artifact@v8
        with:
          name: "builds"
          path: "dist/"
      - name: Create release on Github
        uses: softprops/action-gh-release@v3
        with:
          files: |
            dist/*
          generate_release_notes: true
      - name: "Publish to pypi"
        uses: pypa/gh-action-pypi-publish@v1.14.0
